name: Build and Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for the release'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: npm ci

    - name: Build app for Windows
      run: npm run dist:win

    - name: Build app for Linux
      run: npm run dist:linux

    - name: Build app for macOS
      run: npm run dist:mac

  release:
    needs: build
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*
        tag_name: ${{ github.event.inputs.tag_name }}
        release_name: Release ${{ github.event.inputs.tag_name }}
