name: Build and Release Electron App

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Install Electron Builder
        run: npm install electron-builder@^23.6.0

      - name: Build Electron App
        run: npm run build
        env:
          NODE_ENV: production
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Version from package.json
        id: get_version
        run: echo "::set-output name=version::$(node -p 'require(\"./package.json\").version')"

      - name: Set Environment Variable
        run: echo "VERSION=${{ steps.get_version.outputs.version }}" >> $GITHUB_ENV

      - name: Install gh tool
        uses: cli-actions/setup-gh@v1

      - name: Create GitHub Release
        run: |
          gh release create v${{ steps.get_version.outputs.version }} \
            --title "v${{ steps.get_version.outputs.version }}" \
            --notes "Changes in this Release: - Added feature X - Fixed issue Y" \
            --repo Rajeshwaran2001/infobus \
            --target main \
            --draft false \
            --prerelease false

      - name: Upload Release Asset
        run: |
          gh release upload v${{ steps.get_version.outputs.version }} \
            ./dist/infobus-v${{ steps.get_version.outputs.version }}-${{ matrix.os }}.zip \
            --repo Rajeshwaran2001/infobus